app:
  name: "bluebell_app"
  mode: "dev"
  version: "v0.0.1"
  port: 27777

log:
  level: "info"
  dir: "log"
  filename: "bluebell_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  logInConsole: true

mysql:
  host: "192.168.32.2"
  port: 3306
  user: "root"
  password: "baifendian"
  dbname: "bluebell"
  max_open_connects: 200
  max_idle_connects: 50


redis:
  host: "192.168.32.2"
  port: 6379
  password: "baifendian"
  dbname: 0
  pool_size: 100

snowflake:
  start_time: "2022-08-29"
  machine_ID: 1