name: "bluebell_app"
mode: "dev"
version: "v0.0.1"
port: 27777

log:
  level: "info"
  dir: "log"
  filename: "bluebell_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
  logInConsole: true

mysql:
  host: "8.218.58.79"
  port: 50633
  user: "root"
  password: "742247141d598baba7940f05a93ef456"
  dbname: "bluebell"
  max_open_connects: 200
  max_idle_connects: 50



redis:
  host: "96.45.170.200"
  port: 6379
  password: "742247141d598baba7940f05a93ef456"
  dbname: 0
  pool_size: 100

snowflake:
  start_time: "2022-08-29"
  machine_ID: 1